#define WIN32_LEAN_AND_MEAN
#define HV_PROTOCOL_RAW 1

#include <WinSock2.h>
#include <WS2tcpip.h>
#include <stdio.h>
#include <stdlib.h>
#include <combaseapi.h>
//#include <guiddef.h>


// link with Ws2_32.lib
#pragma comment(lib, "Ws2_32.lib")

//#define DEFAULT_PORT "27015"
#define DEFAULT_BUFFER_LENGTH	512

struct SOCKADDR_HV
{
	ADDRESS_FAMILY Family;
	USHORT Reserved;
	GUID VmId;
	GUID ServiceId;
};

DEFINE_GUID(HV_GUID_PARENT,
	0xa42e7cda, 0xd03f, 0x480c, 0x9c, 0xc2, 0xa, 0x4, 0xde, 0x20, 0xab, 0xb8, 0x78);
DEFINE_GUID(HV_GUID_ZERO,
	0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0);

int main() {

	WSADATA wsaData;
	SOCKADDR_HV clientService;

	// Initialize GUIDs
	CLSID ServiceID;
	wchar_t* clsid_str = L"{b1d00d3e-fe10-4570-ad62-7648779d7a1b}";
	CLSIDFromString(clsid_str, &ServiceID); //GUID of Service, generated by powershell

	// Initialize Winsock
	int iResult = WSAStartup(MAKEWORD(2,2), &wsaData);
	if(iResult != 0)
	{
		printf("WSAStartup failed: %d\n", iResult);
		return 1;
	}

	struct addrinfo	*result = NULL,
					hints;

	CONST GUID *serviceId = &ServiceID;

	ZeroMemory(&clientService, sizeof(clientService));
	clientService.Family = AF_HYPERV;
	clientService.VmId = HV_GUID_ZERO;
	clientService.ServiceId = *serviceId;

	ZeroMemory(&hints, sizeof(hints));
	hints.ai_family = AF_HYPERV;		// Internet address family is unspecified so that either an IPv6 or IPv4 address can be returned
	hints.ai_socktype = SOCK_STREAM;	// Requests the socket type to be a stream socket for the TCP protocol
	hints.ai_protocol = HV_PROTOCOL_RAW;

	hints.ai_addrlen = sizeof(SOCKADDR_HV);
	hints.ai_addr = reinterpret_cast<SOCKADDR *>(&clientService);
	//hints.ai_flags = AI_PASSIVE;

	// Resolve the local address and port to be used by the server
	//iResult = getaddrinfo(NULL, DEFAULT_PORT, &hints, &result);
	//if (iResult != 0)
	//{
	//	printf("getaddrinfo failed: %d\n", iResult);
	//	WSACleanup();
	//	return 1;
	//}

	SOCKET ListenSocket = INVALID_SOCKET;

	// Create a SOCKET for the server to listen for client connections
	//ListenSocket = socket(result->ai_family, result->ai_socktype, result->ai_protocol);
	ListenSocket = socket(hints.ai_family, hints.ai_socktype, hints.ai_protocol);

	if (ListenSocket == INVALID_SOCKET)
	{
		printf("Error at socket(): %d\n", WSAGetLastError());
		freeaddrinfo(result);
		WSACleanup();
		return 1;
	}

	// Setup the TCP listening socket
	//iResult = bind(ListenSocket, result->ai_addr, (int)result->ai_addrlen);
	iResult = bind(ListenSocket, hints.ai_addr, (int)hints.ai_addrlen);

	if (iResult == SOCKET_ERROR)
	{
		printf("bind failed: %d", WSAGetLastError());
		freeaddrinfo(result);
		closesocket(ListenSocket);
		WSACleanup();
		return 1;
	}

	freeaddrinfo(result);

	// To listen on a socket
	if ( listen(ListenSocket, SOMAXCONN) == SOCKET_ERROR)
	{
		printf("listen failed: %d\n", WSAGetLastError());
		closesocket(ListenSocket);
		WSACleanup();
		return 1;
	}

	SOCKET ClientSocket;

	ClientSocket = INVALID_SOCKET;

	// Accept a client socket
	ClientSocket = accept(ListenSocket, NULL, NULL);

	if (ClientSocket == INVALID_SOCKET)
	{
		printf("accept failed: %d\n", WSAGetLastError());
		closesocket(ListenSocket);
		WSACleanup();
		return 1;
	}
	
	char recvbuf[DEFAULT_BUFFER_LENGTH];
	int iSendResult;

	// reveice until the client shutdown the connection
	do {
		iResult = recv(ClientSocket, recvbuf, DEFAULT_BUFFER_LENGTH, 0);
		if (iResult > 0)
		{
			char msg[DEFAULT_BUFFER_LENGTH];
			memset(&msg, 0, sizeof(msg));
			strncpy(msg, recvbuf, iResult);

			printf("Received: %s\n", msg);

			iSendResult = send(ClientSocket, recvbuf, iResult, 0);

			if (iSendResult == SOCKET_ERROR)
			{
				printf("send failed: %d\n", WSAGetLastError());
				closesocket(ClientSocket);
				WSACleanup();
				return 1;
			}

			printf("Bytes sent: %ld\n", iSendResult);
		}
		else if (iResult == 0)
			printf("Connection closed\n");
		else
		{
			printf("recv failed: %d\n", WSAGetLastError());
			closesocket(ClientSocket);
			WSACleanup();
			return 1;
		}
	} while (iResult > 0);

	// Free the resouces
	closesocket(ListenSocket);
	WSACleanup();

	getchar();
	return 0;
}